apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-motd
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - path: /etc/motd
        mode: 0444
        contents:
          source: data:text/plain;base64,V2FybSB3ZWxjb21lIGZyb20gQXJnb0NEIQo=
